ascii_arts = [
'''
 ________  ________  ________  ___  ___
|\   __  \|\   ____\|\   ____\|\  \|\  \
\ \  \|\  \ \  \___|\ \  \___|\ \  \ \  \
 \ \   __  \ \_____  \ \  \    \ \  \ \  \
  \ \  \ \  \|____|\  \ \  \____\ \  \ \  \
   \ \__\ \__\____\_\  \ \_______\ \__\ \__\
    \|__|\|__|\_________\|_______|\|__|\|__|
             \|_________|
 ________ _______  _________  ________  ___  ___
|\  _____\\  ___ \|\___   ___\\   ____\|\  \|\  \
\ \  \__/\ \   __/\|___ \  \_\ \  \___|\ \  \\\  \
 \ \   __\\ \  \_|/__  \ \  \ \ \  \    \ \   __  \
  \ \  \_| \ \  \_|\ \  \ \  \ \ \  \____\ \  \ \  \
   \ \__\   \ \_______\  \ \__\ \ \_______\ \__\ \__\
    \|__|    \|_______|   \|__|  \|_______|\|__|\|__|

Type asciifetch -c to edit the ascii art displayed
''',

'''
 ________  ________  ________  ___  ___
|\   __  \|\   ____\|\   ____\|\  \|\  \
\ \  \|\  \ \  \___|\ \  \___|\ \  \ \  \
 \ \   __  \ \_____  \ \  \    \ \  \ \  \
  \ \  \ \  \|____|\  \ \  \____\ \  \ \  \
   \ \__\ \__\____\_\  \ \_______\ \__\ \__\
    \|__|\|__|\_________\|_______|\|__|\|__|
             \|_________|
 ________ _______  _________  ________  ___  ___
|\  _____\\  ___ \|\___   ___\\   ____\|\  \|\  \
\ \  \__/\ \   __/\|___ \  \_\ \  \___|\ \  \\\  \
 \ \   __\\ \  \_|/__  \ \  \ \ \  \    \ \   __  \
  \ \  \_| \ \  \_|\ \  \ \  \ \ \  \____\ \  \ \  \
   \ \__\   \ \_______\  \ \__\ \ \_______\ \__\ \__\
    \|__|    \|_______|   \|__|  \|_______|\|__|\|__|
'''
]
